defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: snippy_development

test:
  <<: *defaults
  database: snippy_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: snippy
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
